version: 1.0.{build}
image: Visual Studio 2017

environment:

  matrix:

  - PYTHON: "C:\\Python27-x64"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37-x64"


build: off

install:
  - ps: Install-Product node 8.10

test_script:
  - node --version
  - npm --version
